#访问端口
server:
  port: 8085

#数据库
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/small?serverTimezone=UTC&characterEncoding=utf-8
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  #全文检索elasticsearch
#  data:
#    elasticsearch:
#      cluster-name: elasticsearch
#      cluster-nodes: 192.168.200.128:9300
  #文件上传
  servlet:
    multipart:
      max-file-size: 5MB # 限制文件上传的大小
  thymeleaf: #关闭thymeleaf缓存
    cache: false
  #redis
  redis:
    host: 192.168.200.128
  rabbitmq:
    host: 192.168.200.128
    username: guest
    password: guest
  mail:
    username: 872386515@qq.com
    password: tcgwpjkdnaurbdie
    properties:
      mail:
        smtp:
          ssl:
            enable: true
    host: smtp.qq.com
#  profiles:
#    active: dev
#图片上传
fdfs:
  so-timeout: 1501
  connect-timeout: 601
  thumb-image: # 缩略图
    width: 60
    height: 60
  tracker-list: # tracker地址
    - 192.168.200.128:22122
mybatis-plus:
  mapper-locations: classpath:/mapper/*Mapper.xml
  global-config:
    #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
    id-type: 0
    #字段策略 0:"忽略判断",1:"非 NULL 判断"),2:"非空判断"
    field-strategy: 1
    #驼峰下划线转换
    db-column-underline: true
    #刷新mapper 调试神器
    refresh-mapper: true
    #表前缀
    table-prefix: sf_
  configuration:
    map-underscore-to-camel-case: true
  type-aliases-package: com.smallflyingleg.pojo



appid: wx2d7c0cd6bd40b155
partner: 1457151502
partnerkey: pengtaoshuichangweixinshanghu316
notifyurl: http://a31ef7db.ngrok.io/WeChatPay/WeChatPayNotify

#appid: wx2d7c0cd6bd40b155
#partner: 1536422011
#partnerkey: xinlingmeiyabinweixinshanghu0527
#notifyurl: http://a31ef7db.ngrok.io/WeChatPay/WeChatPayNotify
#











#management:
#  security:
#    enabled: false
---


